# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  proto2api:
    image: proto2api
    build:
      context: .
      dockerfile: Backend/src/Proto2.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5007:5007
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
