// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proto2.Persistence.Context;

#nullable disable

namespace Proto2.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240429210821_HomeCare_Data")]
    partial class HomeCare_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proto2.Domain.HomeCareCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("HomeCareCompanies");
                });

            modelBuilder.Entity("Proto2.Domain.HomeCareContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactData")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ContactType")
                        .HasColumnType("int");

                    b.Property<int>("HomeCareCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeCareCompanyId");

                    b.ToTable("HomeCareContacts");
                });

            modelBuilder.Entity("Proto2.Domain.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<string>("NeighborhoodName")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonAdressNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonAdressStreetName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PersonFirstEntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PersonName")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Proto2.Domain.HomeCareContact", b =>
                {
                    b.HasOne("Proto2.Domain.HomeCareCompany", "HomeCareCompany")
                        .WithMany("Contacts")
                        .HasForeignKey("HomeCareCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeCareCompany");
                });

            modelBuilder.Entity("Proto2.Domain.HomeCareCompany", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
